Sources/KetchSDK/index.html

Addresssing https://ketch-com.atlassian.net/browse/KD-11369

KD-11369 Added JavaScript parameters tweaks

---

README.md
Sources/KetchSDK/Core/Entities/Consent.swift
Sources/KetchSDK/Core/Entities/InvokeRight.swift
Sources/KetchSDK/Core/Ketch.swift
Sources/KetchSDK/Core/KetchSDK.swift
Sources/KetchSDK/Core/PolicyProtocol.swift
Sources/KetchSDK/UI/KetchUI.swift
Sources/KetchSDK/UI/PresentationItem/PresentationItem.swift

- removed extra parameter from SDK;
- added ability to override SDK Environment URL;
- updated readme;

[KD-11381] Final polishing

---

Sources/KetchSDK/UI/Extensions/View+KetchViewModifier.swift
Sources/KetchSDK/UI/KetchUI.swift

- fixed banner animation;
- show experience only after config loaded;

fixed banner animation

---

Sources/KetchSDK/UI/KetchUI.swift
Sources/KetchSDK/index.html

Updated error handlers and events that webview triggers
Code cleanup and removal of code pieces that are the result of early experiments

Ketch Tag usage update

---

Sources/KetchSDK/UI/PresentationItem/PresentationItem.swift

fix(protocols): data event

---

Sources/KetchSDK/UI/PresentationItem/WebConfig.swift

- Adds a flag indicating that the call is coming from the mobile SDK. We still need this to determine the mobile SDK case vs the mobile web browser case, but we don't care about the device type (tablet vs. phone)
- https://ketch-com.atlassian.net/browse/KD-11869

feat: add mobileSdk flag

---

Sources/KetchSDK/UI/PresentationItem/WebConfig.swift

- Adds bottom safe area padding for the ios webview
- https://ketch-com.atlassian.net/browse/KD-11942

feat: add bottom safe area inset

---

Sources/KetchSDK/UI/PresentationItem/WebConfig.swift
Sources/KetchSDK/index.html

feat: safe area removal

---

Sources/KetchSDK/Core/Entities/Consent.swift
Sources/KetchSDK/Core/Ketch.swift
Sources/KetchSDK/Core/KetchSDK.swift

Fixes consent event handler decoding and adds protocols field
- https://ketch-com.atlassian.net/browse/KD-11986
- Local

fix: consent event handler

---

Sources/KetchSDK/UI/PresentationItem/PresentationItem+ViewController.swift

> Conditions import of the UIKit package, making our SDK more robust when imported into other swift packages
- Local

chore: condition UIKit import

---

KetchSDK.podspec

chore: bump podspec

---

Sources/KetchSDK/Core/KetchSDK.swift

> Adds `closeWithoutSettingConsent` status
- Local

chore: add closeWithoutSettingConsent

---

Sources/KetchSDK/Core/KetchSDK.swift
Sources/KetchSDK/UI/KetchUI.swift
Sources/KetchSDK/UI/PresentationItem/PresentationItem.swift

> Adds a `onWillShowExperience` listener
- Local with iOS sample app

feat(events): willShowExperience listener

---

KetchSDK.podspec
README.md
Sources/KetchSDK/UI/KetchUI.swift
Sources/KetchSDK/UI/PresentationItem/PresentationItem.swift
Sources/KetchSDK/UI/PresentationItem/WebConfig.swift

Updated posdspec file with the latest SDK version;
Added ability to override such parameters like org, property code, and identities;
Updated Readme with Cocoapods support;

Cocopos and new samples support

---

KetchSDK.podspec

chore: bump version in podspec

---

KetchSDK.podspec

chore: bump tag

---

Sources/KetchSDK/UI/KetchUI.swift
Sources/KetchSDK/UI/PresentationItem/PresentationItem.swift

> Adds hasShownExperience event

feat(events): hasShownExperience

---

Sources/KetchSDK/UI/KetchUI.swift
Sources/KetchSDK/UI/PresentationItem/PresentationItem.swift
Sources/KetchSDK/UI/PresentationItem/WebConfig.swift

added ability to inject css into the Ketch UI;

---

KetchSDK.podspec
README.md
Sources/KetchSDK/UI/KetchUI.swift

bump cocoapods version, updated Readme;

---

KetchSDK.podspec
Sources/KetchSDK/UI/PresentationItem/PresentationItem.swift

> Passes ATT status into webview, to support ATT plugin
- Sample app

feat(ATT): pass apple ATT status to webview
